/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sofianeouardi
 */
public class VoteMajoritaireHome extends javax.swing.JFrame {

    /**
     * Creates new form templateframe
     */
    public VoteMajoritaireHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VoteMajortaireHomePanel = new javax.swing.JPanel();
        evoteimgLabel = new javax.swing.JLabel();
        VoteMajoritaireLabel = new javax.swing.JLabel();
        AvatarimgLabel = new javax.swing.JLabel();
        nomCandidatTextField = new javax.swing.JTextField();
        ListeCandidatPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        saisieTermineeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(720, 480));

        VoteMajortaireHomePanel.setBackground(new java.awt.Color(255, 255, 255));

        evoteimgLabel.setIcon(new javax.swing.ImageIcon("/Users/sofianeouardi/Desktop/img/evote-logo.png")); // NOI18N

        VoteMajoritaireLabel.setBackground(new java.awt.Color(204, 204, 204));
        VoteMajoritaireLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        VoteMajoritaireLabel.setForeground(new java.awt.Color(102, 102, 102));
        VoteMajoritaireLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VoteMajoritaireLabel.setText("Vous avez choisi vote majoritaire à 2 tours");

        AvatarimgLabel.setIcon(new javax.swing.ImageIcon("/Users/sofianeouardi/Desktop/img/avatar comp.png")); // NOI18N

        nomCandidatTextField.setText("Saisissez le nom du candidat à ajouter...");
        nomCandidatTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomCandidatTextFieldMouseClicked(evt);
            }
        });
        nomCandidatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomCandidatTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Candidats :");

        javax.swing.GroupLayout ListeCandidatPanelLayout = new javax.swing.GroupLayout(ListeCandidatPanel);
        ListeCandidatPanel.setLayout(ListeCandidatPanelLayout);
        ListeCandidatPanelLayout.setHorizontalGroup(
            ListeCandidatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListeCandidatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListeCandidatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(ListeCandidatPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 113, Short.MAX_VALUE))
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator5))
                .addContainerGap())
        );
        ListeCandidatPanelLayout.setVerticalGroup(
            ListeCandidatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListeCandidatPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );

        saisieTermineeButton.setBackground(new java.awt.Color(0, 204, 153));
        saisieTermineeButton.setForeground(new java.awt.Color(102, 102, 102));
        saisieTermineeButton.setText("Saisie terminée");
        saisieTermineeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saisieTermineeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VoteMajortaireHomePanelLayout = new javax.swing.GroupLayout(VoteMajortaireHomePanel);
        VoteMajortaireHomePanel.setLayout(VoteMajortaireHomePanelLayout);
        VoteMajortaireHomePanelLayout.setHorizontalGroup(
            VoteMajortaireHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VoteMajortaireHomePanelLayout.createSequentialGroup()
                .addGroup(VoteMajortaireHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(evoteimgLabel)
                    .addComponent(VoteMajoritaireLabel))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(VoteMajortaireHomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListeCandidatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saisieTermineeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VoteMajortaireHomePanelLayout.createSequentialGroup()
                .addGap(0, 229, Short.MAX_VALUE)
                .addGroup(VoteMajortaireHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomCandidatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(VoteMajortaireHomePanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(AvatarimgLabel)))
                .addGap(227, 227, 227))
        );
        VoteMajortaireHomePanelLayout.setVerticalGroup(
            VoteMajortaireHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VoteMajortaireHomePanelLayout.createSequentialGroup()
                .addComponent(evoteimgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VoteMajoritaireLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(AvatarimgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomCandidatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListeCandidatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VoteMajortaireHomePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(saisieTermineeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VoteMajortaireHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VoteMajortaireHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomCandidatTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomCandidatTextFieldMouseClicked
        // TODO add your handling code here:

        nomCandidatTextField.setText("");
    }//GEN-LAST:event_nomCandidatTextFieldMouseClicked

    private void nomCandidatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomCandidatTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomCandidatTextFieldActionPerformed

    private void saisieTermineeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saisieTermineeButtonActionPerformed
        // TODO add your handling code here:
        VoteMajoritaireNbVotant VoteMajoritaireNbVotant = new VoteMajoritaireNbVotant();
        VoteMajoritaireNbVotant.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_saisieTermineeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(templateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(templateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(templateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(templateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new templateframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvatarimgLabel;
    private javax.swing.JPanel ListeCandidatPanel;
    private javax.swing.JLabel VoteMajoritaireLabel;
    private javax.swing.JPanel VoteMajortaireHomePanel;
    private javax.swing.JLabel evoteimgLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField nomCandidatTextField;
    private javax.swing.JButton saisieTermineeButton;
    // End of variables declaration//GEN-END:variables
}
