/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sofianeouardi
 */
public class VoteParQuotientResultatFinal extends javax.swing.JFrame {

    /**
     * Creates new form templateframe
     */
    public VoteParQuotientResultatFinal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        evoteimgLabel = new javax.swing.JLabel();
        VoteQuotientLabel = new javax.swing.JLabel();
        saisieTermineeButton = new javax.swing.JButton();
        choisirmodevoteLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(720, 480));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        evoteimgLabel.setIcon(new javax.swing.ImageIcon("/Users/sofianeouardi/Desktop/img/evote-logo.png")); // NOI18N

        VoteQuotientLabel.setBackground(new java.awt.Color(204, 204, 204));
        VoteQuotientLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        VoteQuotientLabel.setForeground(new java.awt.Color(102, 102, 102));
        VoteQuotientLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VoteQuotientLabel.setText("Vous avez choisi vote par quotient");

        saisieTermineeButton.setBackground(new java.awt.Color(0, 204, 153));
        saisieTermineeButton.setForeground(new java.awt.Color(102, 102, 102));
        saisieTermineeButton.setText("Retour menu principal");
        saisieTermineeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saisieTermineeButtonActionPerformed(evt);
            }
        });

        choisirmodevoteLabel3.setBackground(new java.awt.Color(204, 0, 51));
        choisirmodevoteLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        choisirmodevoteLabel3.setForeground(new java.awt.Color(204, 0, 51));
        choisirmodevoteLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        choisirmodevoteLabel3.setText("Résultat final :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(choisirmodevoteLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(evoteimgLabel)
                            .addComponent(VoteQuotientLabel))
                        .addGap(0, 424, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 550, Short.MAX_VALUE)
                        .addComponent(saisieTermineeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(evoteimgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VoteQuotientLabel)
                .addGap(40, 40, 40)
                .addComponent(choisirmodevoteLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(saisieTermineeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saisieTermineeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saisieTermineeButtonActionPerformed
        // TODO add your handling code here:
        Home Home = new Home();
        Home.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_saisieTermineeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(templateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(templateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(templateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(templateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new templateframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VoteQuotientLabel;
    private javax.swing.JLabel choisirmodevoteLabel3;
    private javax.swing.JLabel evoteimgLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton saisieTermineeButton;
    // End of variables declaration//GEN-END:variables
}
