/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sofianeouardi
 */
public class VoteMajoritaireVoteCandidat extends javax.swing.JFrame {

    /**
     * Creates new form templateframe
     */
    public VoteMajoritaireVoteCandidat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VoteMajoritaireVoteCandidatPanel = new javax.swing.JPanel();
        evoteimgLabel = new javax.swing.JLabel();
        VoteMajoritaireLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PremierTourLabel = new javax.swing.JLabel();
        ChoixCandidatLabel = new javax.swing.JLabel();
        voteimgLabel4 = new javax.swing.JLabel();
        ListeCandidatComboBox = new javax.swing.JComboBox<>();
        saisieTermineeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(720, 480));

        VoteMajoritaireVoteCandidatPanel.setBackground(new java.awt.Color(255, 255, 255));

        evoteimgLabel.setIcon(new javax.swing.ImageIcon("/Users/sofianeouardi/Desktop/img/evote-logo.png")); // NOI18N

        VoteMajoritaireLabel.setBackground(new java.awt.Color(204, 204, 204));
        VoteMajoritaireLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        VoteMajoritaireLabel.setForeground(new java.awt.Color(102, 102, 102));
        VoteMajoritaireLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VoteMajoritaireLabel.setText("Vous avez choisi vote majoritaire à 2 tours");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        PremierTourLabel.setBackground(new java.awt.Color(204, 204, 204));
        PremierTourLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        PremierTourLabel.setForeground(new java.awt.Color(102, 102, 102));
        PremierTourLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PremierTourLabel.setText("1ER Tour :");

        ChoixCandidatLabel.setBackground(new java.awt.Color(204, 0, 51));
        ChoixCandidatLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        ChoixCandidatLabel.setForeground(new java.awt.Color(204, 0, 51));
        ChoixCandidatLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChoixCandidatLabel.setText("Électeur 1, veuillez attribuer votre vote au candidat souhaité");

        voteimgLabel4.setIcon(new javax.swing.ImageIcon("/Users/sofianeouardi/Desktop/img/avatar comp.png")); // NOI18N

        ListeCandidatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emmanuel Macron", "Marine Le Pen", "Eric Zemmour", "Jean-Luc Melanchon" }));
        ListeCandidatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeCandidatComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(voteimgLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(ListeCandidatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(PremierTourLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 102, Short.MAX_VALUE)
                .addComponent(ChoixCandidatLabel)
                .addGap(95, 95, 95))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(PremierTourLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ChoixCandidatLabel)
                .addGap(18, 18, 18)
                .addComponent(voteimgLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListeCandidatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        saisieTermineeButton.setBackground(new java.awt.Color(0, 204, 153));
        saisieTermineeButton.setForeground(new java.awt.Color(102, 102, 102));
        saisieTermineeButton.setText("Soumettre");
        saisieTermineeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saisieTermineeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VoteMajoritaireVoteCandidatPanelLayout = new javax.swing.GroupLayout(VoteMajoritaireVoteCandidatPanel);
        VoteMajoritaireVoteCandidatPanel.setLayout(VoteMajoritaireVoteCandidatPanelLayout);
        VoteMajoritaireVoteCandidatPanelLayout.setHorizontalGroup(
            VoteMajoritaireVoteCandidatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VoteMajoritaireVoteCandidatPanelLayout.createSequentialGroup()
                .addGroup(VoteMajoritaireVoteCandidatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(evoteimgLabel)
                    .addComponent(VoteMajoritaireLabel))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(VoteMajoritaireVoteCandidatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VoteMajoritaireVoteCandidatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VoteMajoritaireVoteCandidatPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saisieTermineeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        VoteMajoritaireVoteCandidatPanelLayout.setVerticalGroup(
            VoteMajoritaireVoteCandidatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VoteMajoritaireVoteCandidatPanelLayout.createSequentialGroup()
                .addComponent(evoteimgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VoteMajoritaireLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(saisieTermineeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(VoteMajoritaireVoteCandidatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VoteMajoritaireVoteCandidatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListeCandidatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeCandidatComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListeCandidatComboBoxActionPerformed

    private void saisieTermineeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saisieTermineeButtonActionPerformed
        // TODO add your handling code here:
        VoteMajoritaireResultatPremierTour VoteMajoritaireResultatPremierTour = new VoteMajoritaireResultatPremierTour();
        VoteMajoritaireResultatPremierTour.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_saisieTermineeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(templateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(templateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(templateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(templateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new templateframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChoixCandidatLabel;
    private javax.swing.JComboBox<String> ListeCandidatComboBox;
    private javax.swing.JLabel PremierTourLabel;
    private javax.swing.JLabel VoteMajoritaireLabel;
    private javax.swing.JPanel VoteMajoritaireVoteCandidatPanel;
    private javax.swing.JLabel evoteimgLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton saisieTermineeButton;
    private javax.swing.JLabel voteimgLabel4;
    // End of variables declaration//GEN-END:variables
}
