/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sofianeouardi
 */
public class VoteMajoritaireNbVotant extends javax.swing.JFrame {

    /**
     * Creates new form templateframe
     */
    public VoteMajoritaireNbVotant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VoteMajoritaireNbVotantPanel = new javax.swing.JPanel();
        evoteimgLabel = new javax.swing.JLabel();
        VoteMajoritaireLabel = new javax.swing.JLabel();
        SaisirNbVotantLabel = new javax.swing.JLabel();
        nbVotantsTextField = new javax.swing.JTextField();
        saisieTermineeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(720, 480));

        VoteMajoritaireNbVotantPanel.setBackground(new java.awt.Color(255, 255, 255));

        evoteimgLabel.setIcon(new javax.swing.ImageIcon("/Users/sofianeouardi/Desktop/img/evote-logo.png")); // NOI18N

        VoteMajoritaireLabel.setBackground(new java.awt.Color(204, 204, 204));
        VoteMajoritaireLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        VoteMajoritaireLabel.setForeground(new java.awt.Color(102, 102, 102));
        VoteMajoritaireLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VoteMajoritaireLabel.setText("Vous avez choisi vote majoritaire à 2 tours");

        SaisirNbVotantLabel.setBackground(new java.awt.Color(204, 204, 204));
        SaisirNbVotantLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        SaisirNbVotantLabel.setForeground(new java.awt.Color(102, 102, 102));
        SaisirNbVotantLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SaisirNbVotantLabel.setText("Saisissez le nombre de votants");

        nbVotantsTextField.setText("Ex : 10");
        nbVotantsTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nbVotantsTextFieldMouseClicked(evt);
            }
        });
        nbVotantsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbVotantsTextFieldActionPerformed(evt);
            }
        });

        saisieTermineeButton.setBackground(new java.awt.Color(0, 204, 153));
        saisieTermineeButton.setForeground(new java.awt.Color(102, 102, 102));
        saisieTermineeButton.setText("Saisie terminée");
        saisieTermineeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saisieTermineeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VoteMajoritaireNbVotantPanelLayout = new javax.swing.GroupLayout(VoteMajoritaireNbVotantPanel);
        VoteMajoritaireNbVotantPanel.setLayout(VoteMajoritaireNbVotantPanelLayout);
        VoteMajoritaireNbVotantPanelLayout.setHorizontalGroup(
            VoteMajoritaireNbVotantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VoteMajoritaireNbVotantPanelLayout.createSequentialGroup()
                .addGroup(VoteMajoritaireNbVotantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(evoteimgLabel)
                    .addComponent(VoteMajoritaireLabel)
                    .addComponent(SaisirNbVotantLabel))
                .addGap(0, 359, Short.MAX_VALUE))
            .addGroup(VoteMajoritaireNbVotantPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nbVotantsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VoteMajoritaireNbVotantPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saisieTermineeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        VoteMajoritaireNbVotantPanelLayout.setVerticalGroup(
            VoteMajoritaireNbVotantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VoteMajoritaireNbVotantPanelLayout.createSequentialGroup()
                .addComponent(evoteimgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VoteMajoritaireLabel)
                .addGap(18, 18, 18)
                .addComponent(SaisirNbVotantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nbVotantsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addComponent(saisieTermineeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VoteMajoritaireNbVotantPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VoteMajoritaireNbVotantPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nbVotantsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbVotantsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbVotantsTextFieldActionPerformed

    private void nbVotantsTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nbVotantsTextFieldMouseClicked
        // TODO add your handling code here:
        nbVotantsTextField.setText("");
    }//GEN-LAST:event_nbVotantsTextFieldMouseClicked

    private void saisieTermineeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saisieTermineeButtonActionPerformed
        // TODO add your handling code here:
        VoteMajoritaireVoteCandidat VoteMajoritaireVoteCandidat = new VoteMajoritaireVoteCandidat();
        VoteMajoritaireVoteCandidat.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_saisieTermineeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(templateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(templateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(templateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(templateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new templateframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SaisirNbVotantLabel;
    private javax.swing.JLabel VoteMajoritaireLabel;
    private javax.swing.JPanel VoteMajoritaireNbVotantPanel;
    private javax.swing.JLabel evoteimgLabel;
    private javax.swing.JTextField nbVotantsTextField;
    private javax.swing.JButton saisieTermineeButton;
    // End of variables declaration//GEN-END:variables
}
