/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sofianeouardi
 */
public class VoteMajoritaireResultatPremierTour extends javax.swing.JFrame {

    /**
     * Creates new form templateframe
     */
    public VoteMajoritaireResultatPremierTour() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VoteMajoritaireResultatPremierTourPanel = new javax.swing.JPanel();
        evoteimgLabel = new javax.swing.JLabel();
        VoteMajoritaireLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ResultatPremierTourLabel = new javax.swing.JLabel();
        CandidatEliminesLabel = new javax.swing.JLabel();
        CandidatOKDeuxiemeTourLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        saisieTermineeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(720, 480));

        VoteMajoritaireResultatPremierTourPanel.setBackground(new java.awt.Color(255, 255, 255));

        evoteimgLabel.setIcon(new javax.swing.ImageIcon("/Users/sofianeouardi/Desktop/img/evote-logo.png")); // NOI18N

        VoteMajoritaireLabel.setBackground(new java.awt.Color(204, 204, 204));
        VoteMajoritaireLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        VoteMajoritaireLabel.setForeground(new java.awt.Color(102, 102, 102));
        VoteMajoritaireLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VoteMajoritaireLabel.setText("Vous avez choisi vote majoritaire à 2 tours");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        ResultatPremierTourLabel.setBackground(new java.awt.Color(204, 204, 204));
        ResultatPremierTourLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        ResultatPremierTourLabel.setForeground(new java.awt.Color(102, 102, 102));
        ResultatPremierTourLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultatPremierTourLabel.setText("Resultats 1ER Tour :");

        CandidatEliminesLabel.setBackground(new java.awt.Color(204, 0, 51));
        CandidatEliminesLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        CandidatEliminesLabel.setForeground(new java.awt.Color(204, 0, 51));
        CandidatEliminesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CandidatEliminesLabel.setText("Candidats éliminés :");

        CandidatOKDeuxiemeTourLabel.setBackground(new java.awt.Color(204, 0, 51));
        CandidatOKDeuxiemeTourLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        CandidatOKDeuxiemeTourLabel.setForeground(new java.awt.Color(204, 0, 51));
        CandidatOKDeuxiemeTourLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CandidatOKDeuxiemeTourLabel.setText("Candidats passant au deuxième tour :");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(CandidatEliminesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(CandidatOKDeuxiemeTourLabel)
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(ResultatPremierTourLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ResultatPremierTourLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CandidatEliminesLabel)
                            .addComponent(CandidatOKDeuxiemeTourLabel))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        saisieTermineeButton.setBackground(new java.awt.Color(0, 204, 153));
        saisieTermineeButton.setForeground(new java.awt.Color(102, 102, 102));
        saisieTermineeButton.setText("Retour menu principal");
        saisieTermineeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saisieTermineeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VoteMajoritaireResultatPremierTourPanelLayout = new javax.swing.GroupLayout(VoteMajoritaireResultatPremierTourPanel);
        VoteMajoritaireResultatPremierTourPanel.setLayout(VoteMajoritaireResultatPremierTourPanelLayout);
        VoteMajoritaireResultatPremierTourPanelLayout.setHorizontalGroup(
            VoteMajoritaireResultatPremierTourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VoteMajoritaireResultatPremierTourPanelLayout.createSequentialGroup()
                .addGroup(VoteMajoritaireResultatPremierTourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(evoteimgLabel)
                    .addComponent(VoteMajoritaireLabel))
                .addGap(0, 356, Short.MAX_VALUE))
            .addGroup(VoteMajoritaireResultatPremierTourPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VoteMajoritaireResultatPremierTourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VoteMajoritaireResultatPremierTourPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saisieTermineeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        VoteMajoritaireResultatPremierTourPanelLayout.setVerticalGroup(
            VoteMajoritaireResultatPremierTourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VoteMajoritaireResultatPremierTourPanelLayout.createSequentialGroup()
                .addComponent(evoteimgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VoteMajoritaireLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(saisieTermineeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VoteMajoritaireResultatPremierTourPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VoteMajoritaireResultatPremierTourPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saisieTermineeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saisieTermineeButtonActionPerformed
        // TODO add your handling code here:
        Home Home = new Home();
        Home.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_saisieTermineeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(templateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(templateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(templateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(templateframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new templateframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CandidatEliminesLabel;
    private javax.swing.JLabel CandidatOKDeuxiemeTourLabel;
    private javax.swing.JLabel ResultatPremierTourLabel;
    private javax.swing.JLabel VoteMajoritaireLabel;
    private javax.swing.JPanel VoteMajoritaireResultatPremierTourPanel;
    private javax.swing.JLabel evoteimgLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton saisieTermineeButton;
    // End of variables declaration//GEN-END:variables
}
